def print_logo():
    print ('\n')
    print ('LLLLLLLLLLL')
    print ('L:::::::::L')
    print ('L:::::::::L')
    print ('LL:::::::LL')
    print ('  L:::::L               uuuuuu    uuuuuu      ccccccccccccccccyyyyyyy           yyyyyyy')
    print ('  L:::::L               u::::u    u::::u    cc:::::::::::::::c y:::::y         y:::::y')
    print ('  L:::::L               u::::u    u::::u   c:::::::::::::::::c  y:::::y       y:::::y')
    print ('  L:::::L               u::::u    u::::u  c:::::::cccccc:::::c   y:::::y     y:::::y')
    print ('  L:::::L               u::::u    u::::u  c::::::c     ccccccc    y:::::y   y:::::y')
    print ('  L:::::L               u::::u    u::::u  c:::::c                  y:::::y y:::::y')
    print ('  L:::::L               u::::u    u::::u  c:::::c                   y:::::y:::::y')
    print ('  L:::::L         LLLLLLu:::::uuuu:::::u  c::::::c     ccccccc       y:::::::::y')
    print ('LL:::::::LLLLLLLLL:::::Lu:::::::::::::::uuc:::::::cccccc:::::c        y:::::::y')
    print ('L::::::::::::::::::::::L u:::::::::::::::u c:::::::::::::::::c         y:::::y')
    print ('L::::::::::::::::::::::L  uu::::::::uu:::u  cc:::::::::::::::c        y:::::y')
    print ('LLLLLLLLLLLLLLLLLLLLLLLL    uuuuuuuu  uuuu    cccccccccccccccc       y:::::y')
    print ('                                                                    y:::::y')
    print ('                                                                   y:::::y')
    print ('                                                                  y:::::y')
    print ('                                                                 y:::::y')
    print ('                                                                yyyyyyy')
    print ('                                   v0.1                                ')
    print ('                              by Nick Tsapakis                         ')
    print ('\n')
