/boot/vmlinuz
/etc/debian_version
/etc/fedora-release
/etc/issue
/etc/issue.net
/etc/mandrake-release
/etc/os-release
/etc/redhat-release
/etc/slackware-release
/etc/suse-release
/etc/SUSE-release
/proc/version
